export default {
  default: {
    "--bg-color": "#f5eded",
    "--border-color": "#3e3636",
    "--knots-crosses-color": "#927070",
    "--primary-text": "#fff",
    "--secondary-text": "#000",
    "--winning-msg-bg": "#ecd6c3",
    "--winning-msg-overlay": "#beb7b76e",
    "--button-bg": "#fff",
    "--button-hover": "#d6d6d6",
    "--button-text": "#000",
    "--win-line-color": "#684e4e",
    "--filter": "#927070"
  },
  dark: {
    "--bg-color": "#0e153a",
    "--border-color": "#1f4287",
    "--knots-crosses-color": "#3d5af1",
    "--primary-text": "#e2f3f5",
    "--secondary-text": "#e2f3f5",
    "--winning-msg-bg": "#22d1ee",
    "--winning-msg-overlay": "#22d1ee6e",
    "--button-bg": "#e2f3f5",
    "--button-hover": "#dee1ec",
    "--button-text": "#0e153a",
    "--win-line-color": "#581b98",
    "--filter": "#e2f3f5"
  },
  solar: {
    "--bg-color": "#4e413b",
    "--border-color": "#857671",
    "--knots-crosses-color": "#ff6d24",
    "--primary-text": "#e2ded3",
    "--secondary-text": "#e2ded3",
    "--winning-msg-bg": "#3e4a61",
    "--winning-msg-overlay": "#3e4a616e",
    "--button-bg": "#e2f3f5",
    "--button-hover": "#dee1ec",
    "--button-text": "#4e413b",
    "--win-line-color": "#e2ded3",
    "--filter": "#e2f3f5"
  },
  color: {
    "--bg-color": "#581b98",
    "--border-color": "#9c1de7",
    "--knots-crosses-color": "#f3558e",
    "--primary-text": "#7c203a",
    "--secondary-text": "#e2f3f5",
    "--winning-msg-bg": "#faee1c",
    "--winning-msg-overlay": "#faee1c6e",
    "--button-bg": "#e2f3f5",
    "--button-hover": "#dee1ec",
    "--button-text": "#7c203a",
    "--win-line-color": "#fccde2",
    "--filter": "#e2f3f5"
  },
  green: {
    "--bg-color": "#3b5441",
    "--border-color": "#2cb978",
    "--knots-crosses-color": "#83e85a",
    "--primary-text": "#e2f3f5",
    "--secondary-text": "#e2f3f5",
    "--winning-msg-bg": "#107a8b",
    "--winning-msg-overlay": "#107a8b6e",
    "--button-bg": "#e2f3f5",
    "--button-hover": "#dee1ec",
    "--button-text": "#7c203a",
    "--win-line-color": "#fccde2",
    "--filter": "#e2f3f5"
  },
  blood: {
    "--bg-color": "#2b2024",
    "--border-color": "#a80038",
    "--knots-crosses-color": "#fd0054",
    "--primary-text": "#fbf9fa",
    "--secondary-text": "#fbf9fa",
    "--winning-msg-bg": "#eb89b5",
    "--winning-msg-overlay": "#ffd7e96e",
    "--button-bg": "#fd0054",
    "--button-hover": "#a80038",
    "--button-text": "#fbf9fa",
    "--win-line-color": "#fccde2",
    "--filter": "#fbf9fa"
  }
};
